# Generated by Django 5.2 on 2025-06-18 15:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('order', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='status',
            field=models.CharField(choices=[('pending', 'pending'), ('paid', 'paid'), ('failed', 'failed'), ('success', 'success'), ('draft', 'draft'), ('canceled', 'canceled')], default='pending', max_length=20),
        ),
        migrations.AlterField(
            model_name='transaction',
            name='cancel_time',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='transaction',
            name='perform_time',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
