# Generated by Django 5.2 on 2025-07-01 04:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('order', '0004_alter_transaction_payment_method_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='transaction',
            name='payment_method',
            field=models.CharField(choices=[('click_up', 'Click'), ('payme', 'Payme')], default='click_up', max_length=20),
        ),
    ]
