# Generated by Django 5.2 on 2025-07-01 05:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('order', '0005_alter_transaction_payment_method'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='payment_id',
            field=models.BigIntegerField(blank=True, null=True),
        ),
    ]
