# Generated by Django 5.2 on 2025-07-13 09:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('order', '0006_order_payment_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='transaction',
            name='payment_method',
            field=models.CharField(choices=[('click_up', 'Click'), ('payme', 'Payme'), ('tribute', 'Tribute')], default='click_up', max_length=20),
        ),
    ]
