# Generated by Django 5.2.8 on 2025-12-09 06:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('order', '0007_alter_transaction_payment_method'),
    ]

    operations = [
        migrations.AlterField(
            model_name='privatechannel',
            name='private_channel_id',
            field=models.CharField(max_length=255),
        ),
        migrations.AlterField(
            model_name='privatechannel',
            name='private_channel_link',
            field=models.URLField(blank=True, null=True),
        ),
    ]
