# Generated by Django 5.2 on 2025-06-19 14:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0002_user_language'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='is_joined_channel',
            field=models.BooleanField(default=False),
        ),
    ]
