# Generated by Django 5.2 on 2025-06-19 15:15

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0003_user_is_joined_channel'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='user',
            name='is_joined_channel',
        ),
    ]
