# Generated by Django 5.2 on 2025-06-30 15:10

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0004_remove_user_is_joined_channel'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='agreed_to_terms',
            field=models.BooleanField(default=False, help_text='Foydalanuvchi ommaviy oferta shartlariga roziligini bildiradi.'),
        ),
        migrations.AddField(
            model_name='user',
            name='is_auto_subscribe',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='user',
            name='subscription_end_date',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='user',
            name='subscription_start_date',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.CreateModel(
            name='UserCard',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('name', models.CharField(default='', max_length=20, verbose_name='name')),
                ('marked_pan', models.CharField(blank=True, max_length=16, null=True)),
                ('expire_date', models.CharField(max_length=4)),
                ('service', models.CharField(choices=[('click', 'Click')], default='click', max_length=25)),
                ('is_main', models.BooleanField(default=False, verbose_name='main')),
                ('is_confirmed', models.BooleanField(default=False)),
                ('card_token', models.CharField(max_length=255, verbose_name='given by click')),
                ('processing', models.CharField(max_length=255, null=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'unique_together': {('user', 'marked_pan', 'card_token')},
            },
        ),
    ]
