# Generated by Django 5.2 on 2025-07-13 09:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0005_user_agreed_to_terms_user_is_auto_subscribe_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='is_foreigner',
            field=models.BooleanField(default=False),
        ),
    ]
