"""
Django settings for config project.

Generated by 'django-admin startproject' using Django 5.2.

For more information on this file, see
https://docs.djangoproject.com/en/5.2/topics/settings/

For the full list of settings and their values, see
https://docs.djangoproject.com/en/5.2/ref/settings/
"""

from pathlib import Path

from decouple import AutoConfig

# Build paths inside the project like this: BASE_DIR / 'subdir'.
BASE_DIR = Path(__file__).resolve().parent.parent
config = AutoConfig(search_path=BASE_DIR.parent / '.env')

# Quick-start development settings - unsuitable for production
# See https://docs.djangoproject.com/en/5.2/howto/deployment/checklist/

# SECURITY WARNING: keep the secret key used in production secret!
SECRET_KEY = config('SECRET_KEY')
BASE_URL = config('BASE_URL', default='http://127.0.0.1:8000')

# SECURITY WARNING: don't run with debug turned on in production!
DEBUG = config('DEBUG', default=False, cast=bool)

ALLOWED_HOSTS = ['*']

# Application definition

INSTALLED_APPS = [
    'django.contrib.admin',
    'django.contrib.auth',
    'django.contrib.contenttypes',
    'django.contrib.sessions',
    'django.contrib.messages',
    'django.contrib.staticfiles',
    "corsheaders",
    'rest_framework',

    'core',
    'users',
    'bot',
    'order',
]

MIDDLEWARE = [
    'django.middleware.security.SecurityMiddleware',
    'django.contrib.sessions.middleware.SessionMiddleware',
    "corsheaders.middleware.CorsMiddleware",
    'django.middleware.common.CommonMiddleware',
    'django.middleware.csrf.CsrfViewMiddleware',
    'django.contrib.auth.middleware.AuthenticationMiddleware',
    'django.contrib.messages.middleware.MessageMiddleware',
    'django.middleware.clickjacking.XFrameOptionsMiddleware',
]

ROOT_URLCONF = 'config.urls'

AUTH_USER_MODEL = 'users.User'

TEMPLATES = [
    {
        'BACKEND': 'django.template.backends.django.DjangoTemplates',
        'DIRS': [],
        'APP_DIRS': True,
        'OPTIONS': {
            'context_processors': [
                'django.template.context_processors.request',
                'django.contrib.auth.context_processors.auth',
                'django.contrib.messages.context_processors.messages',
            ],
        },
    },
]

WSGI_APPLICATION = 'config.wsgi.application'
ASGI_APPLICATION = 'config.asgi.application'

# Database
# https://docs.djangoproject.com/en/5.2/ref/settings/#databases

DATABASES = {
    'default': {
        "ENGINE": "django.db.backends.postgresql",
        "CONN_MAX_AGE": 5,
        "NAME": config("POSTGRES_DB", default='django_aiogram'),
        "USER": config("POSTGRES_USER", default='postgres'),
        "PASSWORD": config("POSTGRES_PASSWORD", default='1'),
        "HOST": config("POSTGRES_HOST", default='localhost'),
        "PORT": config("POSTGRES_PORT", default=5432, cast=int),
    }
}
CACHES = {
    "default": {
        "BACKEND": "django_redis.cache.RedisCache",
        "LOCATION": config('REDIS_URL', default='redis://127.0.0.1:6379/1'),
        "OPTIONS": {
            "CLIENT_CLASS": "django_redis.client.DefaultClient",
        }
    }
}
# Password validation
# https://docs.djangoproject.com/en/5.2/ref/settings/#auth-password-validators

AUTH_PASSWORD_VALIDATORS = [
    {
        'NAME': 'django.contrib.auth.password_validation.UserAttributeSimilarityValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.MinimumLengthValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.CommonPasswordValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.NumericPasswordValidator',
    },
]

# Internationalization
# https://docs.djangoproject.com/en/5.2/topics/i18n/

LANGUAGE_CODE = 'en-us'

TIME_ZONE = 'Asia/Tashkent'

USE_I18N = True

USE_TZ = True

# Static files (CSS, JavaScript, Images)
# https://docs.djangoproject.com/en/5.2/howto/static-files/

STATIC_URL = '/static/'
STATIC_ROOT = BASE_DIR.parent / "cdn/static"

MEDIA_URL = "/media/"
MEDIA_ROOT = BASE_DIR.parent / "cdn/media"

# Default primary key field type
# https://docs.djangoproject.com/en/5.2/ref/settings/#default-auto-field

DEFAULT_AUTO_FIELD = 'django.db.models.BigAutoField'

# Bot settings
BOT_TOKEN = config('BOT_TOKEN')
LIFESPAN_CONTEXT = 'config.lifespan.lifespan_context'
BOT_WEBHOOK_PATH = 'process-bot-updates'
BOT_SECRET_TOKEN = config('BOT_SECRET_TOKEN')

BOT_WEBHOOK_SECRET = config('BOT_WEBHOOK_SECRET')

CSRF_TRUSTED_ORIGINS = [
    "http://*.localhost:1040",
    "http://*.localhost:8003",
    "http://95.46.96.71:1040",
    "https://payment.im-tech.uz",
    'https://yoldakorishamiz.nerofit.uz'
]

CORS_ALLOW_CREDENTIALS = True
CORS_ALLOW_ALL_ORIGINS = True

CLICK_SERVICE_ID = config('CLICK_SERVICE_ID')
CLICK_MERCHANT_ID = config('CLICK_MERCHANT_ID')
CLICK_SECRET_KEY = config('CLICK_SECRET_KEY')
CLICK_MERCHANT_USER_ID = config('CLICK_MERCHANT_USER_ID')

CLICK_AMOUNT_FIELD = "amount"

ADMIN_USERNAME = '@TurgunovKozimjon'

OFERTA_URL = 'https://docs.google.com/spreadsheets/d/1AT2dOBOQjUb8QBdBZfxcgpSpsdNj5xRZ/edit?gid=306014876#gid=306014876'
